### ISSUE TITLE
workflow suggestions

### ISSUE THREAD

**Issue by csae8092** [bundesverfassung-oesterreich/bv-commentary-parser#1]
please have a look into https://github.com/grocerist/grocerist-tei

* ideally we don't want to check in .docx files into version control because zips are not very suitable for vc
* having .docx files floating around in several states on several PCs usually is a mess

**Comment by cfhaak** [comment]
Thanks a lot, was already unsure about the docx on github, thought of it more like a "upload files when done"-thing but that would have surely created a ton of problems.
